
package com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CCPolicySearchIntegration", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration", wsdlLocation = "http://115.112.147.13:8180/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration?WSDL")
public class CCPolicySearchIntegration
    extends Service
{

    private final static URL CCPOLICYSEARCHINTEGRATION_WSDL_LOCATION;
    private final static WebServiceException CCPOLICYSEARCHINTEGRATION_EXCEPTION;
    private final static QName CCPOLICYSEARCHINTEGRATION_QNAME = new QName("http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration", "CCPolicySearchIntegration");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://115.112.147.13:8180/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CCPOLICYSEARCHINTEGRATION_WSDL_LOCATION = url;
        CCPOLICYSEARCHINTEGRATION_EXCEPTION = e;
    }

    public CCPolicySearchIntegration() {
        super(__getWsdlLocation(), CCPOLICYSEARCHINTEGRATION_QNAME);
    }

    public CCPolicySearchIntegration(WebServiceFeature... features) {
        super(__getWsdlLocation(), CCPOLICYSEARCHINTEGRATION_QNAME, features);
    }

    public CCPolicySearchIntegration(URL wsdlLocation) {
        super(wsdlLocation, CCPOLICYSEARCHINTEGRATION_QNAME);
    }

    public CCPolicySearchIntegration(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CCPOLICYSEARCHINTEGRATION_QNAME, features);
    }

    public CCPolicySearchIntegration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCPolicySearchIntegration(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CCPolicySearchIntegrationPortType
     */
    @WebEndpoint(name = "CCPolicySearchIntegrationSoap11Port")
    public CCPolicySearchIntegrationPortType getCCPolicySearchIntegrationSoap11Port() {
        return super.getPort(new QName("http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration", "CCPolicySearchIntegrationSoap11Port"), CCPolicySearchIntegrationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCPolicySearchIntegrationPortType
     */
    @WebEndpoint(name = "CCPolicySearchIntegrationSoap11Port")
    public CCPolicySearchIntegrationPortType getCCPolicySearchIntegrationSoap11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration", "CCPolicySearchIntegrationSoap11Port"), CCPolicySearchIntegrationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CCPOLICYSEARCHINTEGRATION_EXCEPTION!= null) {
            throw CCPOLICYSEARCHINTEGRATION_EXCEPTION;
        }
        return CCPOLICYSEARCHINTEGRATION_WSDL_LOCATION;
    }

}
