
package com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.guidewire.pc.ccintegration.CCPCFilteringCriteria;
import com.guidewire.pc.ccintegration.CCPCSearchCriteria;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CCPolicySearchIntegrationPortType", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration")
@XmlSeeAlso({
    com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration.ObjectFactory.class,
    com.guidewire.pc.ccintegration.ObjectFactory.class,
    com.guidewire.ws.soapheaders.ObjectFactory.class
})
public interface CCPolicySearchIntegrationPortType {


    /**
     * 
     * @param filter
     * @param criteria
     * @return
     *     returns com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration.SearchForPoliciesResponse.Return
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration")
    @RequestWrapper(localName = "searchForPolicies", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration", className = "com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration.SearchForPolicies")
    @ResponseWrapper(localName = "searchForPoliciesResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration", className = "com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration.SearchForPoliciesResponse")
    public com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration.SearchForPoliciesResponse.Return searchForPolicies(
        @WebParam(name = "criteria", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration")
        CCPCSearchCriteria criteria,
        @WebParam(name = "filter", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration")
        CCPCFilteringCriteria filter)
        throws RequiredFieldException_Exception, SOAPException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param filter
     * @param policyNumber
     * @param asOfDate
     * @return
     *     returns com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration.RetrievePolicyResponse.Return
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration")
    @RequestWrapper(localName = "retrievePolicy", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration", className = "com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration.RetrievePolicy")
    @ResponseWrapper(localName = "retrievePolicyResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration", className = "com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration.RetrievePolicyResponse")
    public com.guidewire.pc.ws.gw.webservice.pc.pc800.ccintegration.ccpolicysearchintegration.RetrievePolicyResponse.Return retrievePolicy(
        @WebParam(name = "policyNumber", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration")
        String policyNumber,
        @WebParam(name = "asOfDate", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration")
        XMLGregorianCalendar asOfDate,
        @WebParam(name = "filter", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/ccintegration/CCPolicySearchIntegration")
        CCPCFilteringCriteria filter)
        throws RequiredFieldException_Exception, SOAPException_Exception, WsiAuthenticationException_Exception
    ;

}
