
package servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PCClaimSearchIntegrationAPI", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", wsdlLocation = "http://115.112.147.13:8080/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI?WSDL")
public class PCClaimSearchIntegrationAPI
    extends Service
{

    private final static URL PCCLAIMSEARCHINTEGRATIONAPI_WSDL_LOCATION;
    private final static WebServiceException PCCLAIMSEARCHINTEGRATIONAPI_EXCEPTION;
    private final static QName PCCLAIMSEARCHINTEGRATIONAPI_QNAME = new QName("http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", "PCClaimSearchIntegrationAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://115.112.147.13:8080/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PCCLAIMSEARCHINTEGRATIONAPI_WSDL_LOCATION = url;
        PCCLAIMSEARCHINTEGRATIONAPI_EXCEPTION = e;
    }

    public PCClaimSearchIntegrationAPI() {
        super(__getWsdlLocation(), PCCLAIMSEARCHINTEGRATIONAPI_QNAME);
    }

    public PCClaimSearchIntegrationAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), PCCLAIMSEARCHINTEGRATIONAPI_QNAME, features);
    }

    public PCClaimSearchIntegrationAPI(URL wsdlLocation) {
        super(wsdlLocation, PCCLAIMSEARCHINTEGRATIONAPI_QNAME);
    }

    public PCClaimSearchIntegrationAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PCCLAIMSEARCHINTEGRATIONAPI_QNAME, features);
    }

    public PCClaimSearchIntegrationAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PCClaimSearchIntegrationAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PCClaimSearchIntegrationAPIPortType
     */
    @WebEndpoint(name = "PCClaimSearchIntegrationAPISoap11Port")
    public PCClaimSearchIntegrationAPIPortType getPCClaimSearchIntegrationAPISoap11Port() {
        return super.getPort(new QName("http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", "PCClaimSearchIntegrationAPISoap11Port"), PCClaimSearchIntegrationAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PCClaimSearchIntegrationAPIPortType
     */
    @WebEndpoint(name = "PCClaimSearchIntegrationAPISoap11Port")
    public PCClaimSearchIntegrationAPIPortType getPCClaimSearchIntegrationAPISoap11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", "PCClaimSearchIntegrationAPISoap11Port"), PCClaimSearchIntegrationAPIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PCCLAIMSEARCHINTEGRATIONAPI_EXCEPTION!= null) {
            throw PCCLAIMSEARCHINTEGRATIONAPI_EXCEPTION;
        }
        return PCCLAIMSEARCHINTEGRATIONAPI_WSDL_LOCATION;
    }

}
