
package servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcentities.pcclaimdetail.PCClaimDetail;
import servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcentities.pcclaimsearchcriteria.PCClaimSearchCriteria;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PCClaimSearchIntegrationAPIPortType", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
@XmlSeeAlso({
	servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.ObjectFactory.class,
	servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcentities.pcclaimsearchcriteria.ObjectFactory.class,
	servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcentities.pcclaim.ObjectFactory.class,
	servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcentities.pcclaimdetail.ObjectFactory.class,
	servlet.guidewire.ws.soapheaders.ObjectFactory.class,
	servlet.guidewire.cc.typekey.ObjectFactory.class
})
public interface PCClaimSearchIntegrationAPIPortType {


    /**
     * 
     * @param criteria
     * @return
     *     returns servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.SearchForClaimsResponse.Return
     * @throws WsiAuthenticationException_Exception
     * @throws SOAPException_Exception
     * @throws DataConversionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
    @RequestWrapper(localName = "searchForClaims", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.SearchForClaims")
    @ResponseWrapper(localName = "searchForClaimsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.SearchForClaimsResponse")
    public servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.SearchForClaimsResponse.Return searchForClaims(
        @WebParam(name = "criteria", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
        PCClaimSearchCriteria criteria)
        throws DataConversionException_Exception, SOAPException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param criteria
     * @return
     *     returns servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.SearchForClaimsMultiCriteriaResponse.Return
     * @throws WsiAuthenticationException_Exception
     * @throws DataConversionException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
    @RequestWrapper(localName = "searchForClaimsMultiCriteria", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.SearchForClaimsMultiCriteria")
    @ResponseWrapper(localName = "searchForClaimsMultiCriteriaResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.SearchForClaimsMultiCriteriaResponse")
    public servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.SearchForClaimsMultiCriteriaResponse.Return searchForClaimsMultiCriteria(
        @WebParam(name = "criteria", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
        servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.SearchForClaimsMultiCriteria.Criteria criteria)
        throws DataConversionException_Exception, SOAPException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param criteria
     * @return
     *     returns java.lang.Integer
     * @throws SOAPException_Exception
     * @throws WsiAuthenticationException_Exception
     * @throws DataConversionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
    @RequestWrapper(localName = "getNumberOfClaims", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.GetNumberOfClaims")
    @ResponseWrapper(localName = "getNumberOfClaimsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.GetNumberOfClaimsResponse")
    public Integer getNumberOfClaims(
        @WebParam(name = "criteria", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
        PCClaimSearchCriteria criteria)
        throws DataConversionException_Exception, SOAPException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param criteria
     * @return
     *     returns java.lang.Integer
     * @throws DataConversionException_Exception
     * @throws WsiAuthenticationException_Exception
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
    @RequestWrapper(localName = "getNumberOfClaimsMultiCriteria", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.GetNumberOfClaimsMultiCriteria")
    @ResponseWrapper(localName = "getNumberOfClaimsMultiCriteriaResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.GetNumberOfClaimsMultiCriteriaResponse")
    public Integer getNumberOfClaimsMultiCriteria(
        @WebParam(name = "criteria", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
        servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.GetNumberOfClaimsMultiCriteria.Criteria criteria)
        throws DataConversionException_Exception, SOAPException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param claimNumber
     * @return
     *     returns servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcentities.pcclaimdetail.PCClaimDetail
     * @throws DataConversionException_Exception
     * @throws SOAPException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
    @RequestWrapper(localName = "getClaimByClaimNumber", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.GetClaimByClaimNumber")
    @ResponseWrapper(localName = "getClaimByClaimNumberResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.GetClaimByClaimNumberResponse")
    public PCClaimDetail getClaimByClaimNumber(
        @WebParam(name = "claimNumber", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
        String claimNumber)
        throws DataConversionException_Exception, SOAPException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param claimPublicID
     * @param userName
     * @throws WsiAuthenticationException_Exception
     * @throws SOAPException_Exception
     * @throws DataConversionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "giveUserClaimViewPermission", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.GiveUserClaimViewPermission")
    @ResponseWrapper(localName = "giveUserClaimViewPermissionResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI", className = "servlet.guidewire.cc.ws.gw.webservice.cc.cc800.pcintegration.pcclaimsearchintegrationapi.GiveUserClaimViewPermissionResponse")
    public void giveUserClaimViewPermission(
        @WebParam(name = "claimPublicID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
        String claimPublicID,
        @WebParam(name = "userName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc800/pcintegration/PCClaimSearchIntegrationAPI")
        String userName)
        throws DataConversionException_Exception, SOAPException_Exception, WsiAuthenticationException_Exception
    ;

}
