
package servlet.guidewire.cc.ws.gw.webservice.cc.cc801.claim.claimapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClaimAPI", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc801/claim/ClaimAPI", wsdlLocation = "http://115.112.147.13:8080/cc/ws/gw/webservice/cc/cc801/claim/ClaimAPI?WSDL")
public class ClaimAPI
    extends Service
{

    private final static URL CLAIMAPI_WSDL_LOCATION;
    private final static WebServiceException CLAIMAPI_EXCEPTION;
    private final static QName CLAIMAPI_QNAME = new QName("http://guidewire.com/cc/ws/gw/webservice/cc/cc801/claim/ClaimAPI", "ClaimAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://115.112.147.13:8080/cc/ws/gw/webservice/cc/cc801/claim/ClaimAPI?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLAIMAPI_WSDL_LOCATION = url;
        CLAIMAPI_EXCEPTION = e;
    }

    public ClaimAPI() {
        super(__getWsdlLocation(), CLAIMAPI_QNAME);
    }

    public ClaimAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLAIMAPI_QNAME, features);
    }

    public ClaimAPI(URL wsdlLocation) {
        super(wsdlLocation, CLAIMAPI_QNAME);
    }

    public ClaimAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLAIMAPI_QNAME, features);
    }

    public ClaimAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClaimAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClaimAPIPortType
     */
    @WebEndpoint(name = "ClaimAPISoap11Port")
    public ClaimAPIPortType getClaimAPISoap11Port() {
        return super.getPort(new QName("http://guidewire.com/cc/ws/gw/webservice/cc/cc801/claim/ClaimAPI", "ClaimAPISoap11Port"), ClaimAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClaimAPIPortType
     */
    @WebEndpoint(name = "ClaimAPISoap11Port")
    public ClaimAPIPortType getClaimAPISoap11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://guidewire.com/cc/ws/gw/webservice/cc/cc801/claim/ClaimAPI", "ClaimAPISoap11Port"), ClaimAPIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLAIMAPI_EXCEPTION!= null) {
            throw CLAIMAPI_EXCEPTION;
        }
        return CLAIMAPI_WSDL_LOCATION;
    }

}
